version: "2"

services:

  medication_dispenser_api:
    container_name: medication_dispenser_api
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - database
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - 5432:5432

    volumes:
      - database:/var/lib/postgresql/data

    networks:
      - database


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 80:80
    networks:
      - database

volumes:
  database:

networks:
  database:
